#   ___  ___  ________  _____ ______   _____ ______   _______   ________
#   |\  \|\  \|\   __  \|\   _ \  _   \|\   _ \  _   \|\  ___ \ |\   __  \
#   \ \  \\\  \ \  \|\  \ \  \\\__\ \  \ \  \\\__\ \  \ \   __/|\ \  \|\  \
#   \ \   __  \ \   __  \ \  \\|__| \  \ \  \\|__| \  \ \  \_|/_\ \   _  _\
#   \ \  \ \  \ \  \ \  \ \  \    \ \  \ \  \    \ \  \ \  \_|\ \ \  \\  \|
#   \ \__\ \__\ \__\ \__\ \__\    \ \__\ \__\    \ \__\ \_______\ \__\\ _\
#   \|__|\|__|\|__|\|__|\|__|     \|__|\|__|     \|__|\|_______|\|__|\|__|
# Simple """all-in-one""" plugin for mc.hamium.xyz
# Made by unium (im sorry)

# Variables (VERY case sensitive)
# {PLAYER} - Player name

# Webhooks
webhooks:
  suggestions: ""
  reports: ""
  broadcasts: ""

# Homes (cooldown is in minutes)
homes:
  tpcooldown: 5
  setcooldown: 1440

# Join/Leave messages
joinleave:
  joinmsg: "&7[&a&l+&r&7] &e{PLAYER}"
  leavemsg: "&7[&c&l-&r&7] &e{PLAYER}"

# H-Restart Settings
hrestart:
  1m: "§d§l፨ §nhamiumMC§r §5§l|§r§f Restarting in §c§l1 minute§r§f!"
  3s: "§d§l፨ §nhamiumMC§r §5§l|§r§f Restarting in §c§l3 seconds§r§f!"
  2s: "§d§l፨ §nhamiumMC§r §5§l|§r§f Restarting in §c§l2 seconds§r§f!"
  1s: "§d§l፨ §nhamiumMC§r §5§l|§r§f Restarting in §c§l1 second§r§f!"
  now: "§d§l፨ §nhamiumMC§r §5§l|§r§f Restarting..."
